### PR TITLE
update Minestom

### PR DESCRIPTION
**Pull request by HSGamer**

### CODE REVIEW

**Comment by TogAr2** [comment]
Can you update it again to the current latest version?
Also why are you adding an extra `.Minestom`? Seems redundant to me

**Comment by HSGamer** [comment]
> Can you update it again to the current latest version? Also why are you adding an extra `.Minestom`? Seems redundant to me

It's from Jitpack. I don't know why, but it seems that Jitpack built built the main & testing submodules. You can check Jitpack.

**Comment by TogAr2** [comment]
> It's from Jitpack. I don't know why, but it seems that Jitpack built the main & testing submodules. You can check Jitpack.

I don't see anything like that on jitpack, and for me it works in the format it was before. Can you remove it?

**Comment by HSGamer** [comment]
> I don't see anything like that on jitpack, and for me it works in the format it was before. Can you remove it?

Are you sure you did not see that in the latest commit?

image

**Comment by TogAr2** [comment]
I am not sure what you mean. For clarification, I meant removing the extra `.Minestom` so it becomes `com.github.Minestom:Minestom:93718276c5`, which is working for me.

**Comment by HSGamer** [comment]
> I am not sure what you mean. For clarification, I meant removing the extra `.Minestom` so it becomes `com.github.Minestom:Minestom:93718276c5`, which is working for me.

For me, it's not working, so just to be sure that any machine works.
I've seen someone from the Minestom Discord asking why `com.github.Minestom:Minestom` does not work, so just me making sure.

**Comment by TogAr2** [comment]
Interesting, well in that case I guess it's fine

**Pull request merged**
